version: '3.9'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/usr/src/app/backend/
    depends_on:
      - db
  # frontend:
  #   build: ./frontend
  #   # command: npm run serve
  #   ports: 
  #     - '8080:8080'
  #   volumes:
  #     - ./frontend:/usr/src/app/frontend
  #     - /usr/src/app/frontned/node_modules
  #   depends_on:
  #     - backend
  db:
    image: postgis/postgis:13-master
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
