# Generated by Django 4.2 on 2023-07-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_patient_onlineappointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineAppointment',
        ),
    ]
