# Generated by Django 4.2 on 2023-07-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_alter_availabilityday_day_of_week'),
        ('appointments', '0003_delete_onlineappointment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('time', 'datetime')},
        ),
    ]
