# Generated by Django 4.2 on 2023-07-18 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_monetarytransaction_amount_and_more'),
        ('appointments', '0005_appointment_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='payments.monetarytransaction'),
        ),
    ]
