# Generated by Django 4.2 on 2023-07-23 16:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_transaction'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appointment',
            managers=[
                ('pain_appointments', django.db.models.manager.Manager()),
            ],
        ),
    ]
