# Generated by Django 4.2 on 2023-07-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermodel_groups_usermodel_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
