# Generated by Django 4.2 on 2023-07-18 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_alter_monetarytransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monetarytransaction',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monetarytransaction',
            name='payment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monetarytransaction',
            name='by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='by_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monetarytransaction',
            name='for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='for_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monetarytransaction',
            name='status',
            field=models.CharField(choices=[('Complete', 'complete'), ('Error', 'error'), ('Pending', 'pending'), ('Canceled', 'canceled'), ('Not Started', 'not_started')], default='Pending'),
        ),
        migrations.AlterField(
            model_name='monetarytransaction',
            name='track_number',
            field=models.CharField(unique=True),
        ),
    ]
