# Generated by Django 4.2 on 2023-07-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_monetarytransaction_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monetarytransaction',
            old_name='track_number',
            new_name='trackId',
        ),
    ]
