# Generated by Django 4.2 on 2023-06-02 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import iranian_cities.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iranian_cities', '0005_auto_20221004_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('MW', 'متخصص مامایی'), ('DT', 'دندانپرشک'), ('GC', 'متخصص زنان'), ('OPHM', 'متخصص چشم پزشک'), ('NS', 'جراح مغز و اعصاب'), ('NL', 'متخصص مغز و اعصاب'), ('OM', 'بینایی سنجی'), ('ORLG', 'حلق و گوش و بینی'), ('PST', 'روانپزشک'), ('PDT', 'متخصص اطفال'), ('PLG', 'روانشناس'), ('CL', 'متخصص قلب و عروق'), ('DMT', 'پوست و مو و زیبایی'), ('ILG', 'متخصص بیماری های عفونی و گرمسیری'), ('CPR', 'متخصص کایروپرکتیک'), ('AT', 'متخصص بیهوشی'), ('INN', 'داخلی'), ('SM', 'پزشکی ورزشی'), ('UL', 'متخصص اورولوژی'), ('MG', 'ژنتیک'), ('ST', 'متخصص گفتار درمانی'), ('RT', 'فوق تخصص روماتولوژی'), ('OP', 'متخصص ارتوپدی'), ('GEL', 'متخصص گوارش'), ('PUL', 'متخصص ریه'), ('NPHL', 'فوق تخصص کلیه'), ('ERNL', 'متخصص غدد'), ('DTT', 'متخصص تغذیه'), ('HO', 'فوق تخصص خون و سرطان شناسی'), ('RL', 'رادیولوژی و سونوگرافی'), ('PHST', 'طب فیزیکی و توانبخشی'), ('RDTP', 'رادیوتراپی'), ('GSE', 'جراح عمومی'), ('PTP', 'فیزیوتراپی'), ('PRS', 'متخصص جراح پلاستیک'), ('PCP', 'پزشک عمومی'), ('MFOS', 'جراح فک و صورت'), ('AM', 'شنوایی سنجی')], max_length=5)),
                ('medical_id', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', iranian_cities.fields.CityField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_offices', to='iranian_cities.city')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_offices', to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_secretaries', to='doctors.doctoroffice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_secretary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_patience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('record', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_records', to='doctors.doctor')),
                ('patience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patience_records', to='doctors.patience')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment_setter', models.ForeignKey(limit_choices_to={'user__user_type__in': ['D', 'S']}, on_delete=django.db.models.deletion.CASCADE, related_name='set_appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_appointments', to='doctors.doctoroffice')),
                ('patience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patience_appointments', to='doctors.patience')),
            ],
        ),
    ]
