# Generated by Django 4.2 on 2023-07-06 07:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0002_remove_appointment_appointment_setter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patience',
            new_name='Patient',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_at',
            new_name='appointment_for',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patience',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='medical_id',
            new_name='upin',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='patience',
            new_name='patient',
        ),
    ]
