# Generated by Django 4.2 on 2023-07-10 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctoroffice_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.SmallIntegerField(choices=[('0', 'یکشنبه'), ('1', 'دوشنبه'), ('2', 'سه\u200cشنبه'), ('3', 'چهارشنبه'), ('4', 'پنج\u200cشنبه'), ('5', 'جمعه'), ('6', 'شنبه')])),
                ('is_available', models.BooleanField(default=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_availability', to='doctors.doctoroffice')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_time', to='doctors.availabilityday')),
            ],
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='secretary',
            name='office',
        ),
        migrations.RemoveField(
            model_name='secretary',
            name='user',
        ),
        migrations.AddField(
            model_name='doctor',
            name='visit_cost',
            field=models.IntegerField(blank=True, default=20000, null=True),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Secretary',
        ),
    ]
