# Generated by Django 4.2 on 2023-07-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_availabilityday_availabilitytime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoroffice',
            name='office_title',
            field=models.CharField(default='default', max_length=40),
        ),
        migrations.AlterField(
            model_name='availabilityday',
            name='day_of_week',
            field=models.SmallIntegerField(choices=[(0, 'یکشنبه'), (1, 'دوشنبه'), (2, 'سه\u200cشنبه'), (3, 'چهارشنبه'), (4, 'پنج\u200cشنبه'), (5, 'جمعه'), (6, 'شنبه')]),
        ),
        migrations.AlterUniqueTogether(
            name='availabilityday',
            unique_together={('office', 'day_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='availabilitytime',
            unique_together={('day', 'time')},
        ),
    ]
