# Generated by Django 4.2 on 2023-07-11 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctoroffice_office_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineAppointmentSpecifics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_fee', models.IntegerField()),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_appointment_specs', to='doctors.doctor')),
            ],
            options={
                'verbose_name_plural': 'online appointment specifics',
            },
        ),
        migrations.CreateModel(
            name='OnlineAvailabilityDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'یکشنبه'), (1, 'دوشنبه'), (2, 'سه\u200cشنبه'), (3, 'چهارشنبه'), (4, 'پنج\u200cشنبه'), (5, 'جمعه'), (6, 'شنبه')])),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_days', to='doctors.onlineappointmentspecifics')),
            ],
        ),
        migrations.AddField(
            model_name='doctoroffice',
            name='consultation_fee',
            field=models.IntegerField(default=50000),
        ),
        migrations.CreateModel(
            name='OnlineAvailabilityTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_times', to='doctors.onlineavailabilityday')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineAppointmentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('W', 'واتساپ'), ('T', 'تلگرام'), ('It', 'ایتا'), ('R', 'روبیکا'), ('In', 'اینستاگرام')], max_length=4)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_medias', to='doctors.onlineappointmentspecifics')),
            ],
        ),
    ]
