# Generated by Django 4.2 on 2023-07-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_delete_onlineappointment'),
        ('doctors', '0011_alter_doctor_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineappointmentspecifics',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='onlineavailabilityday',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='onlineavailabilitytime',
            name='day',
        ),
        migrations.DeleteModel(
            name='OnlineAppointmentMedia',
        ),
        migrations.DeleteModel(
            name='OnlineAppointmentSpecifics',
        ),
        migrations.DeleteModel(
            name='OnlineAvailabilityDay',
        ),
        migrations.DeleteModel(
            name='OnlineAvailabilityTime',
        ),
    ]
