# Generated by Django 4.2 on 2023-07-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_remove_onlineappointmentspecifics_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityday',
            name='day_of_week',
            field=models.SmallIntegerField(choices=[(1, 'دوشنبه'), (2, 'سه\u200cشنبه'), (3, 'چهارشنبه'), (4, 'پنج\u200cشنبه'), (5, 'جمعه'), (6, 'شنبه'), (7, 'یکشنبه')]),
        ),
    ]
