# Generated by Django 4.2 on 2023-07-20 12:17

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='behavior_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='elaboration_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='illness',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='skills_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='suggests_doctor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='treatment_result',
            field=models.CharField(choices=[('T', 'درمان شدم'), ('NT', 'درمان نشدم'), ('P', 'درحال درمان شدن هستم'), ('C', 'درمان را ناتمام گذاشتم'), ('O', 'سایر موارد')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
